
= Лабораторная работа №1

== Разработка программного обеспечения средств измреения

[.text-right]
Автор работы: Студент группы КЭ-413 +
Е.В. Долгих 

<<<
:toc:

<<<
== Введение

Работа посвящена конспекту лекции и попытке объяснить нормальными человечечскими словами, что именно было усвоено за две пары по теме "Разработка программного обеспечения средств измерения". +
Целю работы является демонстрация навыков работы с файлами формата ".adoc".

<<<
== Основная часть 

В зависимости от того, как распределяется время и какие совершаются действия во время процесса разработки ПО, результат может оказаться разной степени паршивости. +
Предположим, что нам заказали сделать калькулятор за 3 млн. рублей за срок 3 месяца. Мы согласились. По истечение трех месяцев мы предоставляем клиенту готовый продукт -- калькулятор умеет делать все базовые арифметические функции. Что в итоге? Клиент не доволен: "Мне нужен функционал для мнимых чисел! Переделать." +
Нетрудно догадаться что подобный итерационный процесс может продолжаться до бесконечности (за каждые три месяца мы снова добавляем какую-то функцию), хотя могли бы плотненько сесть все эти месяцы назад и обговорить все возможные пункты по продукту. +
Эта стадия является начальной -- *Анализ требований и планирование*. 
Стадия занимает больше 20% всего времени, отведенного на создание продукта. Определяются все требования к продукту, составляется преположительный график, распределение задач и финансов по команде. К тому же, среди всей команды разработчиков за этот этап отвечают самые умные, коих немного. +
Второй по затратам времени этап -- *Архитектурное проектирование*. Здесь подключается немного больше людей, что очевидно по значимости этого этапа в целом. Здесь занимаются разработкой плана работы всего продукта в целом, набросок архитектуры продукта. Проводят детальное планирование, включающее в себя разбитие всех задач в подзадачи, в фичи и подфичи; определеяется порядок их выполнения. +
Следующий этап -- *Детальное проектирование*. Все что придумывали на прошлом этапе потихоньку начинаем прописывать - описание классов, их методов и связей. Происходит только _описание_, используя UML-диаграммы, что позволяет прописывать архитектуру без привязки к языку программирования. +
*Кодирование и тестирование* -- наконец дошли до прописывания всего что мы придумали на выбранном нами языке. Очень большое количество людей в команде умеют кодить, поэтому этой задачей занимаются все. Несмотря на то что сейчас этим может заниматься ИИ, многие требования он выполнить все еще не может и представляет собой инструмент. К тому же, в каждой команде разработчиков присутствуют правила оформления кода. +
на этом же этапе проводится тестирование и проверка соответствия спецификации всех методов и функций, код тестируется на ошибки; создается защита кода от изменения другими разработчиками. +
Очень важную часть работы выполняют тестировщики жизненно важных или опасных программ, стабильность и правиьность работы которых может стоить множество жизней. +
Последний этап создания ПО -- *Интеграция, квалификационное тестирование и испытания программного средства*. Завершаем создание финальными глобальными тестами и подготаливаем ПО к выпуску.